(require 'autothemer)

(autothemer-deftheme
 arplette "my theme"

 ((((class color) (min-colors #xFFFFFF)))

	(c-bg "#111111")
	(c-bg2 "#333333")
	(c-bg3 "#555555")
	(c-text "#ffffff")
	(c-text2 "#aaaaaa")
	(c-text3 "#888888")
	(c-text4 "#666666")
	(c-red "#ff3333")
	(c-green "#a4ff2e")
	(c-green-dark "#345500")
	(c-yellow "khaki")
	(c-bright-yellow "yellow")
	(c-orange "#ff781f")
	(c-orange-light "#ffaa77")
	(c-purple "magenta")
	(c-cyan "cyan1")
	(c-mint "#66efc4")
	(c-mint-bg "#052f21")
	)

 ((default (:foreground c-text :background c-bg))
	(region (:background c-text2))
	(hl-line (:background c-bg2))
	(highlight (:background c-bg2))
	(line-number (:foreground c-text4 :background c-bg2))
	(line-number-current-line (:foreground c-text :background c-bg3))

	(mode-line (:foreground c-text :background c-bg3))
	(mode-line-active (:foreground c-text :background c-bg3))
	(mode-line-inactive (:foreground c-text2 :background c-bg2))
	(doom-modeline-project-dir (:foreground c-green))
	(doom-modeline-vcs-default (:foreground c-green))
	(doom-modeline-ryo (:foreground c-green))
	(doom-modeline-info (:foreground c-green))
	(minibuffer-prompt (:foreground c-cyan))

	(nerd-icons-blue (:foreground c-cyan))
	;; (nerd-icons-blue-alt)
	;; (nerd-icons-completion-dir-face)
	;; (nerd-icons-cyan)
	;; (nerd-icons-cyan-alt)
	;; (nerd-icons-dblue)
	;; (nerd-icons-dcyan)
	(nerd-icons-dgreen (:foreground c-green-dark))
	;; (nerd-icons-dmaroon)
	;; (nerd-icons-dorange)
	;; (nerd-icons-dpink)
	;; (nerd-icons-dpurple)
	;; (nerd-icons-dred)
	;; (nerd-icons-dsilver)
	;; (nerd-icons-dyellow)
	(nerd-icons-green (:foreground c-green))
	;; (nerd-icons-lblue)
	;; (nerd-icons-lcyan)
	;; (nerd-icons-lgreen)
	;; (nerd-icons-lmaroon)
	;; (nerd-icons-lorange)
	;; (nerd-icons-lpink)
	;; (nerd-icons-lpurple)
	;; (nerd-icons-lred)
	;; (nerd-icons-lsilver)
	;; (nerd-icons-lyellow)
	;; (nerd-icons-maroon)
	;; (nerd-icons-orange)
	;; (nerd-icons-pink)
	;; (nerd-icons-purple)
	;; (nerd-icons-purple-alt)
	;; (nerd-icons-red)
	;; (nerd-icons-red-alt)
	;; (nerd-icons-silver)
	;; (nerd-icons-yellow)
	(nerd-icons-ibuffer-size-face (:foreground c-text2))
	(nerd-icons-ibuffer-mode-face (:foreground c-text2))

	(dired-directory (:background c-bg))
	(which-key-command-description-face (:foreground c-text :background c-bg))
	(which-key-key-face (:foreground c-green :background c-bg))

	(paren-face (:foreground c-text3))
	(parenthesis (:foreground c-text3))
	(font-lock-bracket-face (:foreground c-text3))
	(font-lock-delimiter-face (:foreground c-text3))
	(font-lock-punctuation-face (:foreground c-text3))
	(font-lock-keyword-face (:foreground c-red :weight 'bold))
	(font-lock-constant-face (:foreground c-orange))
	(font-lock-string-face (:foreground c-yellow))
	(font-lock-builtin-face (:foreground c-orange-light))
	(font-lock-comment-face (:foreground c-bright-yellow))
	(font-lock-function-call-face (:foreground c-text))
	(font-lock-function-name-face (:foreground c-green :background c-green-dark))
	(font-lock-variable-use-face (:foreground c-text))
	(font-lock-variable-name-face (:foreground c-mint :background c-mint-bg))
	(font-lock-type-face (:foreground c-cyan))

	(flymake-error (:underline (:color c-red)))
	(flymake-warning (:underline (:color c-bright-yellow)))
	(eglot-diagnostic-tag-unnecessary-face (:underline (:color c-bright-yellow)))

	(typescript-ts-jsx-tag-face (:foreground c-cyan))
	(typescript-ts-jsx-attribute-face (:foreground c-orange))
	))

(provide-theme 'arplette)
